### ISSUE TITLE
thank u very much

### ISSUE THREAD

**Issue by RtYkk** [neutronest/anitamasaver#4]
Where r u from ? I come from China. How do u know that anitama will be closed. I'm waiting for your completed work.

**Comment by neutronest** [comment]
Hi. The information come from Zhihu. However there is no official claim that the Anitama will be close yet. We must be more patient....

This project is just a practice project for Golang. It now has support download articles as json file. If you want user-friendly data,  https://github.com/SCBeta2718/AnitamaArticle is recommended and you can browser the content as local files.

Best regards.
